services:
  - type: web
    name: bug-training-game
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production 