services:
  - type: web
    name: bug-training-game
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
    healthCheckPath: /health 